# Generated by Django 4.2.11 on 2025-06-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalAccessUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("np", models.CharField(max_length=254, unique=True)),
                ("nombre", models.CharField(max_length=254)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("usuario_creo", models.CharField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                ("ver_nfg", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "calculador.global_access_user",
            },
        ),
    ]
